### ISSUE TITLE
Functional Summarize k01ek and Jasonlin1198

### ISSUE THREAD

**Issue by LHBL2003** [netbox-community/netbox-qrcode#28]
Unfortunately, the version of Jasonlin1198 in Netbox 3.2.2 does not work.
Therefore I compared and merged the code from Jasonlin1198 and k01ek.

But apparently this does not fix the problems.
Currently I lack the necessary knowledge what the problem is.

Maybe you @Jasonlin1198 have the possibility to check the status.

I would like to bring Jasonlin1198's version back to life.

https://github.com/LHBL2003/netbox-qrcode/tree/Compare-k01ek-and-Jasonlin1198

Thank you for your support

**Comment by k01ek** [comment]
Hi @LHBL2003 ! The functional from @Jasonlin1198 need to be refactored. It seems to be easily to create new one from scratch.
