### ISSUE TITLE
Install Issue (Linux Newbie)

### ISSUE THREAD

**Issue by milhouz** [netbox-community/netbox-qrcode#60]
Trying to install the plugin on Netbox v3.4.5

Everything looks to have taken fine up until I add 'netbox_qrcode' as the plugin. As soon as that variable is in the configuration.py I get the following error when restarting up the netbox service.

> (venv) XXXXXXXX@netbox:~$ sudo systemctl status netbox
> ● netbox.service - NetBox WSGI Service
>      Loaded: loaded (/etc/systemd/system/netbox.service; enabled; vendor preset: enabled)
>      Active: activating (auto-restart) (Result: exit-code) since Thu 2024-02-08 20:27:56 UTC; 2s ago
>        Docs: https://netbox.readthedocs.io/en/stable/
>     Process: 3914208 ExecStart=/opt/netbox/venv/bin/gunicorn --pid /var/tmp/netbox.pid --pythonpath /opt/netbox/netbox --config /opt/netbox/gunicorn.py netbox.wsgi (code=exited, status=1/FAILURE)
>    Main PID: 3914208 (code=exited, status=1/FAILURE)
> 
> Feb 08 20:27:56 netbox systemd[1]: netbox.service: Main process exited, code=exited, status=1/FAILURE
> Feb 08 20:27:56 netbox systemd[1]: netbox.service: Failed with result 'exit-code'.

I tried to install this via the venv as well as in the base bash shell but to no avail. Am I missing something obvious? I used the config provided in the readme as a test.

Also not sure what the local_requirements.txt is if someone could shed some light on that piece.

thanks!

**Comment by cmcknz77** [comment]
Hi @milhouz 
I hope this helps - It's more about the general plugin installation or upgrade process after upgrading NetBox but I found it in the Netbox Slack channel: https://www.youtube.com/watch?v=usbrj8ej4cQ
You can join that at https://netdev-community.slack.com

**Comment by cruse1977** [comment]
HI, Closing this issue due to no further updates since Feb
