### ISSUE TITLE
Netbox QR Code Menu page is missing

### ISSUE THREAD

**Issue by teomcam** [netbox-community/netbox-qrcode#65]
I have successfully installed the plug-in following the instructions given. I see, Devices, racks and cables have QR codes in details pages. However; I cannot locate the "Netbox QR Code Menu" page to print QR codes in bulk.

**Comment by k01ek** [comment]
Hi @teomcam ! The plugin currently does not have support for bulk print qr labels.

**Comment by teomcam** [comment]
Thanks for the update k01ek. It seems a step back from the better state. Is there any future plan to reintroduce?
