### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by LeGmask** [netbox-community/netbox-qrcode#67]
I've added all the needed config :

```py
# Enable installed plugins. Add the name of each plugin to the list.
PLUGINS = [
    "netbox_topology_views",
    'netbox_interface_sync',
    'netbox_qrcode',
]

# Plugins configuration settings. These settings are used by various plugins that the user may have installed.
# Each key in the dictionary is the name of an installed plugin and its value is a dictionary of settings.
PLUGINS_CONFIG = {
    'netbox_qrcode': {
        'with_text': True,
        'text_fields': ['name', 'serial'],
        'font': 'TahomaBold',
        'custom_text': 'Property of net7',
        'text_location': 'right',
        'qr_version': 1,
        'qr_error_correction': 1,
        'qr_box_size': 4,
        'qr_border': 4,
        # per object options
        'cable': {
            'text_fields': [
                '_termination_a_device', 
                'termination_a',
                '_termination_b_device', 
                'termination_b'
        ]},
        'rack': None,
        'device': {
            'qr_box_size': 6,
        }
    }
}
```
And requirement.txt :

```
netbox-topology-views
netbox-interface-sync
netbox-qrcode
```

But no qrcode appear...

**Comment by LeGmask** [comment]
Would like to add that I use a docker image :)

**Comment by felbinger** [comment]
I have a similar issue. Can you confirm that Django Admin (Login to netbox as admin -> Admin -> Installed Plugins) shows the plugin as installed?
![image](https://github.com/netbox-community/netbox-qrcode/assets/26925347/2a571b70-3548-44fe-b9b1-b5912df8a318)

**Comment by cruse1977** [comment]
hi @LeGmask , I've fired up a 3.7.x image using the develop/ directory and been unable to replicate this.

- Can you advise on any docker logs for the netbox container ?
- Can you also advise which netbox section you're looking at where you'd expect the QR Code.

 To fire up a 3.7.x instance via the develop dir:
 
 edit develop/DockerFile - changing:

-  ARG python_ver=3.7 to ARG python_ver=3.12
-  ARG netbox_ver=v3.7.8

 then:
 
-  docker compose pull
-  docker compose build
-  docker compose up
-  docker exec -it develop-netbox-1 (top of my head) /opt/netbox/netbox/manage.py createsuperuser
-  http://localhost:8000

  add some data and you should see QR codes.

**Comment by LeGmask** [comment]
Actually I've finally figured out, I was setting up plugins in the configuration.py instead of the plugin.py files. And that wasn't working. After updating this all was working normally.

**Comment by cruse1977** [comment]
Thanks for the confirming, closing the issue down
