### ISSUE TITLE
Netbox versão 3.7.7 python 3.12.3 não aparece a função qr code.

### ISSUE THREAD

**Issue by GABRIELnLuiz** [netbox-community/netbox-qrcode#70]
Já troqu.ei a versão do python e nada funciona, já reintalei revisei as configurações.
Ele fica no status como instalado mas não aparece nada.
![netbox plugin](https://github.com/netbox-community/netbox-qrcode/assets/160254246/7ce55b6f-87a7-4fe5-8bb1-babf265fac84)
![Netbox plugins](https://github.com/netbox-community/netbox-qrcode/assets/160254246/1e2a7d70-c911-4ffc-af9d-b56cf19692e8)
![Netbox versão](https://github.com/netbox-community/netbox-qrcode/assets/160254246/924d48e6-6bcb-4cb4-9eed-4513c370b8ef)

**Comment by ALMGS1979** [comment]
estou o mesmo problema mas na versão 4.3.0 do netbox. Você conseguiu resolver ? @GABRIELnLuiz

**Comment by GABRIELnLuiz** [comment]
Ainda não troquei a versão e ainda nada. Oque posso fazer?

Em qui., 23 de mai. de 2024 às 17:03, ALMGS1979 ***@***.***>
escreveu:

**Comment by GABRIELnLuiz** [comment]
Não consegui resolver meu querido, estou pegando o link html e criando o qr
code no canva.
