### ISSUE TITLE
plugin installs will not show up on any dcim page. 4.0.2/0.0.12

### ISSUE THREAD

**Issue by HomerJaySimpson13** [netbox-community/netbox-qrcode#75]
i have netbox 4.0.2 running fine.  i installed the qrcode plugin and it shows on the admin>system that the plug is loaded.  But when i go to any page that would need a qrcode, there is none.  it doesn't show anything, i ran the debug log and it shows it loading, i really have no idea where to look to even see what is wrong.  Thanks for any assistance.  i'm not even sure this is the place to post this question.

**Comment by cruse1977** [comment]
Hi, absolutely the right place, I'll see if I can replicate this.

**Comment by HomerJaySimpson13** [comment]
out standing.  please let me know if i can give you any information.  it was a new install as i am just starting.  its running on a rocky 9.4 distro and i was using the venv environment.

**Comment by rcalpha** [comment]
I'm having the same issue. I installed 4.0.5 of Netbox and the latest qecode and It shows nothing. In the admin/system the plugin is loaded

**Comment by cruse1977** [comment]
Hi, so I installed a brand new version of netbox-docker and v4.0.5. put some demo data in and enabled qr code and I see this working as expected on the device page:

<img width="1134" alt="image" src="https://github.com/netbox-community/netbox-qrcode/assets/5545071/381dcaaf-01fe-4c5e-ab8e-bc6cf53902ad">

 Can you provide more detail; is there anything in logs, etc ?

**Comment by cruse1977** [comment]
> [netbox.log](https://github.com/user-attachments/files/15806198/netbox.log)
> Thanks for doing this ; it was just a random thought.

> i also upgraded to 4.0.5 to see if that made a difference, and it did not. i have attached the debug log for me loading the page for a device.

 Hm that log shows a few errors but all are NetBox template based rather than QR.  Is that log from a simple device (ie: 1ru single device) or a fairly complex (module bays, etc etc)
 
  You should see a QR code on devices and racks ([you can see the list via <model>QRCode classes](https://github.com/netbox-community/netbox-qrcode/blob/master/netbox_qrcode/template_content.py))

**Comment by HomerJaySimpson13** [comment]
[netbox.log](https://github.com/user-attachments/files/15807514/netbox.log)
![Screenshot 2024-06-12 083859](https://github.com/netbox-community/netbox-qrcode/assets/27863263/dff4d2bd-da8e-42c4-bcbb-f15e958fdd3a)


The Earlier one is from a complex device.  This log is a simple cable manager so there is no ports or anything.

so i dont see anything anywhere.

**Comment by cruse1977** [comment]
> so i dont see anything anywhere.

 Which is unhelpful.  I'm going to try this on a dedicated VM this eve to see if that makes a difference. In theory it shouldn't; can I ask which OS you're running on please ?

**Comment by HomerJaySimpson13** [comment]
The OS is : 
NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"

**Comment by jeffgdotorg** [comment]
Unable to reproduce in an Ubuntu 22.04.4 VM created from their cloud-init image.
![image](https://github.com/netbox-community/netbox-qrcode/assets/1209268/6dd551ee-651c-41d7-8e11-14898ba52574)

**Comment by cruse1977** [comment]
> The OS is : NAME="Rocky Linux" VERSION="9.4 (Blue Onyx)" ID="rocky" ID_LIKE="rhel centos fedora" VERSION_ID="9.4" PLATFORM_ID="platform:el9" PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"

Hi Homer, which python version are you running as 9.4 ships with 3.9 which is unsupported by NetBox 4.x

**Comment by HomerJaySimpson13** [comment]
i am using Python 3.12.1 (main, Feb 19 2024, 00:00:00) [GCC 11.4.1 20231218 (Red Hat 11.4.1-3)] 

ok. what do you recommend for the type of installation as i dont remember what i used.  i can put up another box and try it again.

**Comment by cruse1977** [comment]
Hi Homer,  still can't replicate - 

(venv) [root@localhost netbox]# uname -a
Linux localhost.localdomain 5.14.0-427.20.1.el9_4.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Jun 7 14:51:39 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
(venv) [root@localhost netbox]# cat /etc/rocky-release
Rocky Linux release 9.4 (Blue Onyx)


<img width="584" alt="image" src="https://github.com/netbox-community/netbox-qrcode/assets/5545071/4b82e2ad-a250-46f0-845d-1b2226ee3c7d">

**Comment by HomerJaySimpson13** [comment]
i am currently rebuilding the server.  i'll let you know if it works when i get done.  on the current server i am getting the same versions of all the software execpt netbox-qrcode, i am getting version 0.0.13.

**Comment by jeffgdotorg** [comment]
@HomerJaySimpson13 are you also the Redditor behind [this thread](https://www.reddit.com/r/Netbox/comments/1dbvi51/netbox_402_and_qrcode/)?

**Comment by HomerJaySimpson13** [comment]
if i have debuging logging turned on, should i be seeing anything about qrcode?  when i grep the log, i see nothing with qr in it.

**Comment by supertasksupertask** [comment]
1. I have tried that rhel8.8 does not have a menu or picture with a QR code like rocky8.5, although the plug-in has been successfully installed.

2、The only difference is the libjpeg version, which is.
Libjpeg-turbo-1.5.3-12.el8.x86_64 instead of libjpeg-turbo-2.0.90-7.el9.x86_64, because installation of version 8.x conflicts

**Comment by rcalpha** [comment]
I installed on a brand new ubuntu server 22.04.4 netbox, migrated the data and it's working.... There is issue with ubuntu 20.04.6 with python 3 installed by another way. ubuntu 20.04.6 doesn't have supported python3 version required by netbox

**Comment by cruse1977** [comment]
Thanks for doing this and it fits what I think is happening with rocky.
Rocky's  python version is 3.9 which is unsupported netbox 4.  I have a
feeling the non os distro python being installed on these rocky instances
is causing the problem. It has to be that or a minimal installation or
similar.

**Comment by brourk** [comment]
I had this problem on AlmaLinux 8.10 after installing python 3.12 and Netbox 4.06.  I think the problem may be that pkg_resources (netbox_qrcode/utilities.py) is deprecated and removed in Python 3.12.   What fixed it for me was "pip install setuptools" and restart netbox.

**Comment by cruse1977** [comment]
thanks @brourk ; @rcalpha @supertasksupertask @HomerJaySimpson13  - can you try this fix as above please ?

I'll look at replacing pkg_resources with importlib for a future version

**Comment by HomerJaySimpson13** [comment]
i just ran the pip install setuptools and it fixed it.

**Comment by harryajc** [comment]
Was having this issue on Ubuntu 24.04, with netbox 4.0.9, "pip install setuptools" fixed the issue

**Comment by MisterProblems** [comment]
> I had this problem on AlmaLinux 8.10 after installing python 3.12 and Netbox 4.06. I think the problem may be that pkg_resources (netbox_qrcode/utilities.py) is deprecated and removed in Python 3.12. What fixed it for me was "pip install setuptools" and restart netbox.

Thanks ! It works for me. (python 3.12 , netbox 4.0.9)

**Comment by k01ek** [comment]
may be we just need to include setuptools to install_requires
